# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: generic

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create user travis_ci_test;' -U postgres

env:
  global:
    - TEST_CONN_STRING="user=travis_ci_test"

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
matrix:
  # Make the build finish as soon as all of the non-"allowed_failures" builds
  # are finished building.  Don't wait for the "allowed_failures" to finish.
  fast_finish: true
  include:
  # We grab the appropriate GHC and cabal-install versions from hvr's PPA. See:
  # https://github.com/hvr/multi-ghc-travis
  #- env: BUILD=cabal GHCVER=7.0.4 CABALVER=1.16 HAPPYVER=1.19.5 ALEXVER=3.1.7
  #  compiler: ": #GHC 7.0.4"
  #  addons: {apt: {packages: [cabal-install-1.16,ghc-7.0.4,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
  #- env: BUILD=cabal GHCVER=7.2.2 CABALVER=1.16 HAPPYVER=1.19.5 ALEXVER=3.1.7
  #  compiler: ": #GHC 7.2.2"
  #  addons: {apt: {packages: [cabal-install-1.16,ghc-7.2.2,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
  #- env: BUILD=cabal GHCVER=7.4.2 CABALVER=1.16 HAPPYVER=1.19.5 ALEXVER=3.1.7
  #  compiler: ": #GHC 7.4.2"
  #  addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.2,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
  # - env: BUILD=cabal GHCVER=7.6.3 CABALVER=1.16 HAPPYVER=1.19.5 ALEXVER=3.1.7
  #   compiler: ": #GHC 7.6.3"
  #   addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}
  # - env: BUILD=cabal GHCVER=7.8.4 CABALVER=1.18 HAPPYVER=1.19.5 ALEXVER=3.1.7
  #   compiler: ": #GHC 7.8.4"
  #   addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22 HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC 7.10.3"
    addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.0.2 CABALVER=1.24 HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC 8.0.2"
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.2.2 CABALVER=1.24 HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC 8.2.2"
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.2,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.4.4 CABALVER=2.2 HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC 8.4.4"
    addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.4,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.6.3 CABALVER=2.4 HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC 8.6.3"
    addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.3,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.6.4 CABALVER=2.4 HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC 8.6.4"
    addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.4,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.6.5 CABALVER=2.4 HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC 8.6.5"
    addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.5,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=head CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
    compiler: ": #GHC HEAD"
    addons: {apt: {packages: [cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.7], sources: [hvr-ghc]}}

  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-6.0.yml" DB=postgresql
    compiler: ": #stack 7.10.3 (lts-6)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-7.22.yml" DB=postgresql
    compiler: ": #stack 8.0.1 (lts-7)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-8.0.yml" DB=postgresql
    compiler: ": #stack 8.0.2 (lts-8)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-9.0.yml" DB=postgresql
    compiler: ": #stack 8.0.2 (lts-9)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-10.0.yml" DB=postgresql
    compiler: ": #stack 8.2.2 (lts-10)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-11.0.yml" DB=postgresql
    compiler: ": #stack 8.2.2 (lts-11)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-12.13.yml" DB=postgresql
    compiler: ": #stack 8.4.4 (lts-12)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-13.0.yml" DB=postgresql
    compiler: ": #stack 8.6.3 (lts-13)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-13.12.yml" DB=postgresql
    compiler: ": #stack 8.6.4 (lts-13)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-13.20.yml" DB=postgresql
    compiler: ": #stack 8.6.5 (lts-13)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-14.0.yml" DB=postgresql
    compiler: ": #stack 8.6.5 (lts-14)"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-13.0.yml --resolver nightly" DB=postgresql
    compiler: ": #stack nightly"
    addons: {apt: {packages: [libgmp-dev]}}

  # Build on macOS in addition to Linux

  # - env: BUILD=stack ARGS="--resolver lts-3"
  #   compiler: ": #stack 7.10.2 osx"
  #   os: osx

  # - env: BUILD=stack ARGS="--resolver lts-6"
  #   compiler: ": #stack 7.10.3 osx"
  #   os: osx

  # - env: BUILD=stack ARGS="--resolver lts-7"
  #   compiler: ": #stack 8.0.1 osx"
  #   os: osx

  # - env: BUILD=stack ARGS="--resolver lts-8"
  #   compiler: ": #stack 8.0.2 osx"
  #   os: osx

  - env: BUILD=stack ARGS="--stack-yaml stack-lts-12.13.yml --resolver nightly" DB=postgresql
    compiler: ": #stack nightly osx"
    os: osx

  allow_failures:
  - env: BUILD=cabal GHCVER=head CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7 DB=postgresql
  - env: BUILD=stack ARGS="--stack-yaml stack-lts-12.13.yml --resolver nightly" DB=postgresql
  - os: osx

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# We want to always allow newer versions of packages when building on GHC HEAD
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi

# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

  # Use the more reliable S3 mirror of Hackage
  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  set -ex
  case "$DB" in
    postgresql)
      cd orville-postgresql
      ;;
    *)
      echo "unrecognized database subproject. Unable to continue"
      exit -1
      ;;
  esac
  case "$BUILD" in
    stack)
      stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      ;;
    cabal)
      ghc --version
      (ghc --print-project-git-commit-id 2>/dev/null || echo '?')
      cabal --version
      travis_retry cabal update

      # Get the list of packages from the stack.yaml file
      PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')

      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
      ;;
  esac
  set +ex

script:
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      ;;
    cabal)
      cabal install --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES

      ORIGDIR=$(pwd)
      for dir in $PACKAGES
      do
        cd $dir
        cabal check || [ "$CABALVER" == "1.16" ]
        cabal sdist
        PKGVER=$(cabal info . | awk '{print $2;exit}')
        SRC_TGZ=$PKGVER.tar.gz
        cd dist
        tar zxfv "$SRC_TGZ"
        cd "$PKGVER"
        cabal configure --enable-tests
        cabal build
        cabal test
        cd $ORIGDIR
      done
      ;;
  esac
  set +ex
